/* eslint-disable */
// Generated by scripts/generate-ipc-types.ts. DO NOT EDIT.

import type { CredentialItem, CredentialState, TicketResponse, TicketResult, TicketType } from './orm_types'

export interface IpcInvokeMap {
  'clear-ticket-history': {
    params: []
    return: Promise<void>
  }
  'get-domain-user': {
    params: []
    return: Promise<string>
  }
  'get-ticket-history': {
    params: []
    return: Promise<TicketResult[]>
  }
  'getCurrent': {
    params: []
    return: Promise<CredentialItem>
  }
  'msg': {
    params: [msg: string]
    return: Observable<string>
  }
  'open-link': {
    params: [url: string]
    return: Promise<void>
  }
  'readCredential': {
    params: []
    return: Promise<CredentialState>
  }
  'save-ticket-history': {
    params: [item: TicketResult]
    return: Promise<void>
  }
  'saveCredential': {
    params: [data: CredentialState]
    return: Promise<true>
  }
  'ticket': {
    params: [data: TicketType]
    return: Promise<TicketResponse>
  }
}

export type IpcChannel = keyof IpcInvokeMap

export type IpcInvokeArgs<T extends IpcChannel> = IpcInvokeMap[T]['params']
export type IpcInvokeReturn<T extends IpcChannel> = IpcInvokeMap[T]['return'] extends Promise<unknown>
  ? IpcInvokeMap[T]['return']
  : Promise<IpcInvokeMap[T]['return']>

export {}
