/* eslint-disable */
// Generated by scripts/generate-ipc-types.mjs. DO NOT EDIT.

import type { CredentialState, TicketResponse, TicketType } from './orm_types'

export interface IpcInvokeMap {
  'get-domain-user': {
    params: []
    return: Promise<string>
  }
  'msg': {
    params: [msg: string]
    return: Observable<string>
  }
  'readCredential': {
    params: []
    return: Promise<CredentialState>
  }
  'saveCredential': {
    params: [data: CredentialState]
    return: Promise<true>
  }
  'ticket': {
    params: [data: TicketType]
    return: Promise<TicketResponse>
  }
}

export type IpcChannel = keyof IpcInvokeMap

export type IpcInvokeArgs<T extends IpcChannel> = IpcInvokeMap[T]['params']
export type IpcInvokeReturn<T extends IpcChannel> = IpcInvokeMap[T]['return'] extends Promise<unknown>
  ? IpcInvokeMap[T]['return']
  : Promise<IpcInvokeMap[T]['return']>

export {}
