/* eslint-disable */
// Generated by scripts/generate-ipc-types.mjs. DO NOT EDIT.

import type { CredentialState, TicketResponse, TicketType } from './orm_types'

export interface IpcInvokeMap {
  'get-domain-user': {
    params: []
    return: string
  }
  'msg': {
    params: [msg: string]
    return: string
  }
  'readCredential': {
    params: []
    return: CredentialState
  }
  'saveCredential': {
    params: [data: CredentialState]
    return: true
  }
  'ticket': {
    params: [data: TicketType]
    return: TicketResponse
  }
}

export type IpcChannel = keyof IpcInvokeMap

export type IpcInvokeArgs<T extends IpcChannel> = IpcInvokeMap[T]['params']
export type IpcInvokeReturn<T extends IpcChannel> = Promise<IpcInvokeMap[T]['return']>

export {}
