/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/routeTest/_layout': RouteRecordInfo<
      '/routeTest/_layout',
      '/routeTest/_layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/routeTest/ViewOne': RouteRecordInfo<
      '/routeTest/ViewOne',
      '/routeTest/ViewOne',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/routeTest/ViewTwo': RouteRecordInfo<
      '/routeTest/ViewTwo',
      '/routeTest/ViewTwo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/Credentials': RouteRecordInfo<
      '/settings/Credentials',
      '/settings/Credentials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ticket/Ticket': RouteRecordInfo<
      '/ticket/Ticket',
      '/ticket/Ticket',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/render/views/routeTest/_layout.vue': {
      routes:
        | '/routeTest/_layout'
      views:
        | never
    }
    'src/render/views/routeTest/ViewOne.vue': {
      routes:
        | '/routeTest/ViewOne'
      views:
        | never
    }
    'src/render/views/routeTest/ViewTwo.vue': {
      routes:
        | '/routeTest/ViewTwo'
      views:
        | never
    }
    'src/render/views/settings/Credentials.vue': {
      routes:
        | '/settings/Credentials'
      views:
        | never
    }
    'src/render/views/ticket/Ticket.vue': {
      routes:
        | '/ticket/Ticket'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
