/* eslint-disable */
// Generated by scripts/generate-preload-api.mjs. DO NOT EDIT.

import { ipcRenderer } from 'electron'
import type { IpcChannel, IpcInvokeArgs, IpcInvokeMap, IpcInvokeReturn } from '../../types/ipc-methods'

type PreloadInvokeReturn<T extends IpcChannel, TAsync extends boolean> =
  TAsync extends true ? IpcInvokeReturn<T> : IpcInvokeMap[T]['return']

export const ipcInvoke = {
  getDomainUser: (...args: IpcInvokeArgs<'get-domain-user'>): PreloadInvokeReturn<'get-domain-user', true> =>
    ipcRenderer.invoke('get-domain-user', ...args) as unknown as PreloadInvokeReturn<'get-domain-user', true>,
  msg: (...args: IpcInvokeArgs<'msg'>): PreloadInvokeReturn<'msg', false> =>
    ipcRenderer.invoke('msg', ...args) as unknown as PreloadInvokeReturn<'msg', false>,
  readCredential: (...args: IpcInvokeArgs<'readCredential'>): PreloadInvokeReturn<'readCredential', true> =>
    ipcRenderer.invoke('readCredential', ...args) as unknown as PreloadInvokeReturn<'readCredential', true>,
  saveCredential: (...args: IpcInvokeArgs<'saveCredential'>): PreloadInvokeReturn<'saveCredential', true> =>
    ipcRenderer.invoke('saveCredential', ...args) as unknown as PreloadInvokeReturn<'saveCredential', true>,
  ticket: (...args: IpcInvokeArgs<'ticket'>): PreloadInvokeReturn<'ticket', true> =>
    ipcRenderer.invoke('ticket', ...args) as unknown as PreloadInvokeReturn<'ticket', true>,
} as const
