import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { mkdirSync, writeFileSync } from "node:fs";
import ts from "typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, "..");
const tsconfigPath = join(projectRoot, "tsconfig.node.json");
const outputPath = join(projectRoot, "src", "preload", "electron.ipc-auto.ts");

const normalizePath = (value: string): string =>
  value.replace(/\\/g, "/").toLowerCase();

function getNodeDecorators(node: ts.Node): readonly ts.Decorator[] {
  const byApi = ts.canHaveDecorators(node) ? ts.getDecorators(node) : undefined;
  if (byApi?.length) return byApi;

  const modifiers = (
    node as ts.Node & { modifiers?: ts.NodeArray<ts.ModifierLike> }
  ).modifiers;
  if (!modifiers?.length) return [];

  return modifiers.filter(ts.isDecorator);
}

function getDecoratorName(decorator: ts.Decorator): string | undefined {
  const expr = decorator.expression;
  if (!ts.isCallExpression(expr)) return undefined;
  if (ts.isIdentifier(expr.expression)) return expr.expression.text;
  if (
    ts.isPropertyAccessExpression(expr.expression) &&
    ts.isIdentifier(expr.expression.name)
  ) {
    return expr.expression.name.text;
  }
  return undefined;
}

function getIpcChannel(method: ts.MethodDeclaration): string | undefined {
  const decorators = getNodeDecorators(method);
  if (!decorators.length) return undefined;

  for (const decorator of decorators) {
    const expr = decorator.expression;
    if (!ts.isCallExpression(expr)) continue;
    const name = getDecoratorName(decorator);
    if (name !== "IpcHandle") continue;

    const channelArg = expr.arguments[0];
    if (
      ts.isStringLiteral(channelArg) ||
      ts.isNoSubstitutionTemplateLiteral(channelArg)
    ) {
      return channelArg.text;
    }
  }

  return undefined;
}

function hasAsyncModifier(method: ts.MethodDeclaration): boolean {
  if (!method.modifiers?.length) return false;
  return method.modifiers.some(
    (modifier) => modifier.kind === ts.SyntaxKind.AsyncKeyword,
  );
}

function channelToMethodName(channel: string): string {
  const parts = channel
    .split(/[^a-zA-Z0-9]+/)
    .map((part) => part.trim())
    .filter(Boolean);

  if (parts.length === 0) return "invokeUnknown";

  return parts
    .map((part, index) => {
      if (index === 0) return part.charAt(0).toLowerCase() + part.slice(1);
      return part.charAt(0).toUpperCase() + part.slice(1);
    })
    .join("");
}

const configResult = ts.readConfigFile(tsconfigPath, ts.sys.readFile);
if (configResult.error) {
  throw new Error(
    ts.flattenDiagnosticMessageText(configResult.error.messageText, "\n"),
  );
}

const parsed = ts.parseJsonConfigFileContent(
  configResult.config,
  ts.sys,
  projectRoot,
);
const program = ts.createProgram({
  rootNames: parsed.fileNames,
  options: parsed.options,
});

const srcMainPathFragment = "/src/main/";
interface CollectedMethod {
  channel: string;
  isAsync: boolean;
}

const methodsByChannel = new Map<string, CollectedMethod>();

for (const sourceFile of program.getSourceFiles()) {
  if (sourceFile.isDeclarationFile) continue;

  const normalizedFileName = normalizePath(sourceFile.fileName);
  if (!normalizedFileName.includes(srcMainPathFragment)) continue;
  if (!normalizedFileName.includes(".controller")) continue;

  ts.forEachChild(sourceFile, function visit(node: ts.Node): void {
    if (ts.isClassDeclaration(node)) {
      for (const member of node.members) {
        if (!ts.isMethodDeclaration(member)) continue;

        const channel = getIpcChannel(member);
        if (!channel) continue;

        methodsByChannel.set(channel, {
          channel,
          isAsync: hasAsyncModifier(member),
        });
      }
    }

    ts.forEachChild(node, visit);
  });
}

const sortedMethods = [...methodsByChannel.values()].sort((a, b) =>
  a.channel.localeCompare(b.channel),
);
const methodNameUsed = new Set<string>();

const channelBindings = sortedMethods.map((method) => {
  const channel = method.channel;
  const baseName = channelToMethodName(channel);
  let methodName = baseName;
  let suffix = 2;

  while (methodNameUsed.has(methodName)) {
    methodName = `${baseName}${suffix}`;
    suffix += 1;
  }

  methodNameUsed.add(methodName);

  return {
    channel,
    methodName,
    isAsync: method.isAsync,
  };
});

const lines: string[] = [];
lines.push("/* eslint-disable */");
lines.push("// Generated by scripts/generate-preload-api.ts. DO NOT EDIT.");
lines.push("");
lines.push("import { ipcRenderer } from 'electron'");
lines.push(
  "import type { IpcChannel, IpcInvokeArgs, IpcInvokeMap, IpcInvokeReturn } from '../../types/ipc-methods'",
);
lines.push("");
lines.push(
  "type PreloadInvokeReturn<T extends IpcChannel, TAsync extends boolean> =",
);
lines.push(
  "  TAsync extends true ? IpcInvokeReturn<T> : IpcInvokeMap[T]['return']",
);
lines.push("");
lines.push("export const ipcInvoke = {");

for (const item of channelBindings) {
  lines.push(
    `  ${item.methodName}: (...args: IpcInvokeArgs<'${item.channel}'>): PreloadInvokeReturn<'${item.channel}', ${item.isAsync}> =>`,
  );
  lines.push(
    `    ipcRenderer.invoke('${item.channel}', ...args) as unknown as PreloadInvokeReturn<'${item.channel}', ${item.isAsync}>,`,
  );
}

lines.push("} as const");
lines.push("");

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, lines.join("\n"), "utf8");

console.log(`Generated preload IPC API: ${outputPath}`);
