/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/routeTest/_layout': RouteRecordInfo<
      '/routeTest/_layout',
      '/routeTest/_layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/routeTest/ViewOne': RouteRecordInfo<
      '/routeTest/ViewOne',
      '/routeTest/ViewOne',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/routeTest/ViewTwo': RouteRecordInfo<
      '/routeTest/ViewTwo',
      '/routeTest/ViewTwo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/Credentials1': RouteRecordInfo<
      '/settings/Credentials1',
      '/settings/Credentials1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ticket/Ticket1': RouteRecordInfo<
      '/ticket/Ticket1',
      '/ticket/Ticket1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/render/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/render/views/routeTest/_layout.vue': {
      routes:
        | '/routeTest/_layout'
      views:
        | never
    }
    'src/render/views/routeTest/ViewOne.vue': {
      routes:
        | '/routeTest/ViewOne'
      views:
        | never
    }
    'src/render/views/routeTest/ViewTwo.vue': {
      routes:
        | '/routeTest/ViewTwo'
      views:
        | never
    }
    'src/render/views/settings/Credentials1.vue': {
      routes:
        | '/settings/Credentials1'
      views:
        | never
    }
    'src/render/views/ticket/Ticket1.vue': {
      routes:
        | '/ticket/Ticket1'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
